"""update answer text field

Revision ID: 22c9b0c5e4c5
Revises: 8ef5082f2e19
Create Date: 2024-10-18 20:58:43.414537

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "22c9b0c5e4c5"
down_revision: str | None = "8ef5082f2e19"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "answer",
        "text",
        existing_type=sa.VARCHAR(length=500),
        type_=sqlmodel.sql.sqltypes.AutoString(length=3000),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "answer",
        "text",
        existing_type=sqlmodel.sql.sqltypes.AutoString(length=3000),
        type_=sa.VARCHAR(length=500),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
