"""prompt model added

Revision ID: 79f0476f8250
Revises: 93db8815a923
Create Date: 2024-11-04 07:03:43.624709

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = "79f0476f8250"
down_revision: Union[str, None] = "93db8815a923"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "prompts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "api_version", sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False
        ),
        sa.Column("text", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.alter_column(
        "podcast_segment_summaries",
        "title",
        existing_type=sa.VARCHAR(length=150),
        nullable=False,
    )
    op.alter_column(
        "podcast_segment_summaries",
        "url_at_time",
        existing_type=sa.VARCHAR(length=100),
        nullable=False,
    )
    op.alter_column(
        "podcast_segment_summaries",
        "summary",
        existing_type=sa.VARCHAR(length=1000),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "podcast_segment_summaries",
        "summary",
        existing_type=sa.VARCHAR(length=1000),
        nullable=True,
    )
    op.alter_column(
        "podcast_segment_summaries",
        "url_at_time",
        existing_type=sa.VARCHAR(length=100),
        nullable=True,
    )
    op.alter_column(
        "podcast_segment_summaries",
        "title",
        existing_type=sa.VARCHAR(length=150),
        nullable=True,
    )
    op.drop_table("prompts")
    # ### end Alembic commands ###
