"""Initial migration: create podcast_segment_summaries, question, and answer tables

Revision ID: 8ef5082f2e19
Revises:
Create Date: 2024-10-13 17:50:18.553436

"""

from collections.abc import Sequence

import pgvector
import pgvector.sqlalchemy
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8ef5082f2e19"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table(
        "answer",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("text", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "question",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("text", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("answer_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["answer_id"],
            ["answer.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "podcast_segment_summaries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=150), nullable=True),
        sa.Column("url_at_time", sa.String(length=100), nullable=True),
        sa.Column("summary", sa.String(length=1000), nullable=True),
        sa.Column(
            "embedding",
            pgvector.sqlalchemy.Vector(1024),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("podcast_segment_summaries")
    op.drop_table("question")
    op.drop_table("answer")
    # ### end Alembic commands ###
