"""text field VARCHAR increases

Revision ID: 93db8815a923
Revises: 22c9b0c5e4c5
Create Date: 2024-10-21 21:15:10.627926

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "93db8815a923"
down_revision: str | None = "22c9b0c5e4c5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "answer",
        "text",
        existing_type=sa.VARCHAR(length=3000),
        type_=sqlmodel.sql.sqltypes.AutoString(length=10000),
        existing_nullable=False,
    )
    op.alter_column(
        "question",
        "text",
        existing_type=sa.VARCHAR(length=500),
        type_=sqlmodel.sql.sqltypes.AutoString(length=2500),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "question",
        "text",
        existing_type=sqlmodel.sql.sqltypes.AutoString(length=2500),
        type_=sa.VARCHAR(length=500),
        existing_nullable=False,
    )
    op.alter_column(
        "answer",
        "text",
        existing_type=sqlmodel.sql.sqltypes.AutoString(length=10000),
        type_=sa.VARCHAR(length=3000),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
