"""answer text field increased

Revision ID: a7510651bc92
Revises: 79f0476f8250
Create Date: 2024-11-12 20:59:08.613118

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a7510651bc92"
down_revision: Union[str, None] = "79f0476f8250"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "answer",
        "text",
        existing_type=sa.VARCHAR(length=10000),
        type_=sa.Text(),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "answer",
        "text",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(length=10000),
        nullable=False,
    )
    # ### end Alembic commands ###
