name: Code Quality

on: [push, pull_request, workflow_dispatch]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  quality:
    name: Code Quality Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          uv venv
          uv pip install -r pyproject.toml
        working-directory: ./backend
      - name: Lint with ruff
        run: |
          uv pip install ruff
          uv run ruff check .
        working-directory: ./backend
      - name: Lint with mypy
        run: |
          uv pip install mypy
          uv run mypy --strict app/
        working-directory: ./backend

  integration-tests:
    name: Run Integration Tests
    runs-on: ubuntu-latest
    needs: quality
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Compose
        run: |
          docker compose -f docker-compose.test.yml up --build
        env:
          ENVIRONMENT: "staging"
          FRONTEND_HOST: "http://localhost"
          PROJECT_NAME: "test_project"
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_MODEL: ${{ secrets.OPENAI_MODEL }}
          JINA_EMBEDDER_MODEL: ${{ secrets.JINA_EMBEDDER_MODEL }}
          JINA_API_KEY: ${{ secrets.JINA_API_KEY }}
          POSTGRES_USER: "postgres"
          POSTGRES_PASSWORD: "postgres"
          POSTGRES_DB: "zoe-vector-db"
      - name: Tear Down Docker Compose
        if: always()
        run: docker compose -f docker-compose.yml down