name: Backend Integration Tests

on:
    push:
        branches:
          - main
    pull_request:
    types:
        - opened
        - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  integration-tests:
    name: Run Integration Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Compose
        run: |
          # Ensure clean state
          docker compose -f docker-compose.test.yml down -v --remove-orphans
          # Run tests
          docker compose -f docker-compose.test.yml up --build --abort-on-container-exit --exit-code-from backend
        env:
          ENVIRONMENT: "staging"
          FRONTEND_HOST: "http://localhost"
          PROJECT_NAME: "test_project"
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_MODEL: ${{ secrets.OPENAI_MODEL }}
          JINA_EMBEDDER_MODEL: ${{ secrets.JINA_EMBEDDER_MODEL }}
          JINA_API_KEY: ${{ secrets.JINA_API_KEY }}
          POSTGRES_USER: "postgres"
          POSTGRES_PASSWORD: "postgres"
          POSTGRES_DB: "zoe-vector-db"
      - name: Tear Down Docker Compose
        if: always()
        run: docker compose -f docker-compose.test.yml down
