name: Linting Backend Code

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  linting-backend:
    name: Linting Backend Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          uv venv
          uv pip install -r pyproject.toml
        working-directory: ./backend
      - name: Lint with ruff
        run: |
          uv pip install ruff
          uv run ruff check .
        working-directory: ./backend
      - name: Lint with mypy
        run: |
          uv pip install mypy
          uv run mypy --strict app/
        working-directory: ./backend
